version: '3'


services:
  api:
    build:
      context: './apps/api'
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - ./apps/api/:/app
  web:
    build:
      context: './apps/web'
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./apps/web/:/app
      - /app/.next
